#title = "Task Toml"

[task]
consumer_tag = "task:worker:tag"
default_queue = "task:queue:default"
broker = "redis://192.168.0.1:6379"
backend = "redis://192.168.0.1:6379"
expire_in = 3600
max_worker = 50